name: Java CI with Maven and SAST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "java"
          
      - uses: actions/checkout@v3
      - run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
